<?php
/**
 * All MTC meeting contacts.
 * @todo build  UI for this and save these in the db
 */
$mtc_meeting_contacts = array(
  'Active Transportation Working Group' => array(
    'name' => 'Megan Espiritu',
    'email' => 'mmagill@bayareametro.gov',
  ),
  'Air Quality Conformity Task Force' => array(
    'name' => 'Megan Espiritu',
    'email' => 'mlespiritu@bayareametro.gov',
  ),
  'Arterial Operations Committee' => array(
    'name' => 'Jay Stagi',
    'email' => 'jstagi@bayareametro.gov',
  ),
  'Bay Area Partnership' => array(
    'name' => 'Beba Jimenez',
    'email' => 'bjimenez@bayareametro.gov',
  ),
  'Bay Area Regional Collaborative' => array(
    'name' => 'Vijay Kesavan',
    'email' => 'vkesavan@bayareametro.gov',
  ),
  'Bay Area Toll Authority' => array(
    'name' => 'Rosy Leyva',
    'email' => 'rleyva@bayareametro.gov',
  ),
  'Clipper Executive Board' => array(
    'name' => 'Martha Silver',
    'email' => 'msilver@bayareametro.gov',
  ),
  'Clipper?? Executive Board' => array(
    'name' => 'Martha Silver',
    'email' => 'msilver@bayareametro.gov',
  ),
  'Equity and Access Subcommittee' => array(
    'name' => 'Martha Silver',
    'email' => 'msilver@bayareametro.gov',
  ),
  'Joint MTC Planning Committee with the ABAG Administrative Committee' => array(
    'name' => 'Martha Silver',
    'email' => 'msilver@bayareametro.gov',
  ),
  'Local Streets & Roads Working Group' => array(
    'name' => 'Marcella Aranda',
    'email' => 'maranda@bayareametro.gov',
  ),
  'Partnership Technical Advisory Committee' => array(
    'name' => 'Marcella Aranda',
    'email' => 'maranda@bayareametro.gov',
  ),
  'Programming and Allocations Committee' => array(
    'name' => 'Kimberly Ward',
    'email' => 'kward@bayareametro.gov',
  ),
  'Regional Advisory Working Group' => array(
    'name' => 'Martha Silver',
    'email' => 'msilver@bayareametro.gov',
  ),
  'Regional Equity Working Group' => array(
    'name' => 'Megan Espiritu',
    'email' => 'mlespiritu@bayareametro.gov',
  ),
  'Regional Airport Planning Committee' => array(
    'name' => 'Megan Espiritu',
    'email' => 'mlespiritu@bayareametro.gov',
  ),
  'Regional Prosperity Plan Steering Committee' => array(
    'name' => 'Megan Espiritu',
    'email' => 'mlespiritu@bayareametro.gov',
  ),
  'Transit Finance Working Group' => array(
    'name' => 'Theresa Hannon',
    'email' => 'thannon@bayareametro.gov',
  ),
  'Joint Partnership Local Streets and Roads/Programming and Delivery Working Group' => array(
    'name' => 'Marcella Aranda',
    'email' => 'maranda@bayareametro.gov',
  ),
  'Local Streets and Roads Working Group' => array(
    'name' => 'Marcella Aranda',
    'email' => 'maranda@bayareametro.gov',
  ),
  'Partnership Programming and Delivery Working Group' => array(
    'name' => 'Marcella Aranda',
    'email' => 'maranda@bayareametro.gov',
  ),
  'Plan Bay Area Performance Working Group' => array(
    'name' => 'Megan Espiritu',
    'email' => 'mlespiritu@bayareametro.gov',
  ),
  'Policy Advisory Council' => array(
    'name' => 'Martha Silver',
    'email' => 'msilver@bayareametro.gov',
  ),
  'Service Authority for Freeways and Expressways' => array(
    'name' => 'Rosy Leyva',
    'email' => 'rleyva@bayareametro.gov',
  ),
);
